apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: op4-kube-frontend
  labels:
    app: frontapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontapp
  template:
    metadata:
      labels:
        app: frontapp
    spec:
      containers:
      - name: frontend
        image: quay.io/drsylent/cubix/block4/optional-frontend:springboot3
        env:
        - name: BACKEND_URL
          value: http://backend.op4-kube-backend:8080
        ports:
        - containerPort: 8080
          name: web
