env:
- name: FRONTEND_DEFAULT_MESSAGE
  value: "overwritten value"

image:
  repository: quay.io/drsylent/cubix/block4/optional-frontend
  # Overrides the image tag whose default is the chart appVersion.
  tag: "springboot3"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: application.cubix.localhost
      paths:
        - path: /frontend
          pathType: Prefix